# Auto-generated by openapi-python-client — do not edit manually.
# Regenerate against a running dev gateway (python/scripts/aegis-core.compose.yml):
#   openapi-python-client generate --url <gateway>/api/v1/openapi.json
# then refresh python/openapi.json from the same gateway. (The old
# `make generate-sdk` target lived in the archived aegis-core repo Makefile;
# this repo has no Makefile.)
